[build]
  base = "/"
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20.10.0"
  GO_VERSION = "1.21.5"
  RUBY_VERSION = "3.2.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200